language: go

go:
  - 1.14.x

before_install:
  - sudo apt-get -y install ipfs
  - ipfs init
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
