sudo: true
language: go

go:
  - 1.14.x

before_install:
  - wget -O ipfs.tar.gz https://dist.ipfs.io/go-ipfs/v0.5.1/go-ipfs_v0.5.1_linux-amd64.tar.gz
  - tar -xvf ipfs.tar.gz
  - sudo go-ipfs/install.sh
  - ipfs init
  - go get -t -v ./...

script:
  - make
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
  - ./stark-test -h
  - make clean

after_success:
  - bash <(curl -s https://codecov.io/bash)
