//  Schema for STARK database
//  -------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: stark.proto

package stark

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
//Status is currently un-used.
type Status int32

const (
	Status_UN_INITIALIZED Status = 0
	Status_untagged       Status = 1
	Status_tagged         Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UN_INITIALIZED",
		1: "untagged",
		2: "tagged",
	}
	Status_value = map[string]int32{
		"UN_INITIALIZED": 0,
		"untagged":       1,
		"tagged":         2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_stark_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_stark_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_stark_proto_rawDescGZIP(), []int{0}
}

//
//DbMeta.
//
//This message is used to encode runtime
//information for a StarkDb.
type DbMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project     string            `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`                                                                                     // project name for the current database
	Snapshot    string            `protobuf:"bytes,2,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`                                                                                   // CID for the current database state
	NodeAddress string            `protobuf:"bytes,3,opt,name=NodeAddress,proto3" json:"NodeAddress,omitempty"`                                                                             // the IPFS node address for the database
	Pinning     bool              `protobuf:"varint,5,opt,name=Pinning,proto3" json:"Pinning,omitempty"`                                                                                    // if true, database is pinning entries
	Announcing  bool              `protobuf:"varint,6,opt,name=Announcing,proto3" json:"Announcing,omitempty"`                                                                              // if true, database is announcing entries on PubSub
	CurrEntries int32             `protobuf:"varint,7,opt,name=CurrEntries,proto3" json:"CurrEntries,omitempty"`                                                                            // current number of entries in the database
	Pairs       map[string]string `protobuf:"bytes,8,rep,name=Pairs,proto3" json:"Pairs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // pairs of Keys -> Record CIDs held in the database
}

func (x *DbMeta) Reset() {
	*x = DbMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stark_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbMeta) ProtoMessage() {}

func (x *DbMeta) ProtoReflect() protoreflect.Message {
	mi := &file_stark_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbMeta.ProtoReflect.Descriptor instead.
func (*DbMeta) Descriptor() ([]byte, []int) {
	return file_stark_proto_rawDescGZIP(), []int{0}
}

func (x *DbMeta) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DbMeta) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *DbMeta) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *DbMeta) GetPinning() bool {
	if x != nil {
		return x.Pinning
	}
	return false
}

func (x *DbMeta) GetAnnouncing() bool {
	if x != nil {
		return x.Announcing
	}
	return false
}

func (x *DbMeta) GetCurrEntries() int32 {
	if x != nil {
		return x.CurrEntries
	}
	return 0
}

func (x *DbMeta) GetPairs() map[string]string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

//
//Key.
//
//This message is used to send queries from
//gRPC clients to a stark database that implements
//the StarkDb interface.
type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stark_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_stark_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_stark_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

//
//Record.
//
//This message is used to describe a sequencing metadata.
//Record's will be able to encode runs, samples and libraries.
//WIP.
type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// reserved:
	Uuid        string           `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                        // universally unique id for the record
	PreviousCID string           `protobuf:"bytes,2,opt,name=previousCID,proto3" json:"previousCID,omitempty"`          // the last known CID this record was pulled from (set during a Get operation)
	History     []*RecordComment `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`                  // describes the history of the record - can be used to get timestamps for creation and last updated
	Encrypted   bool             `protobuf:"varint,4,opt,name=encrypted,proto3" json:"encrypted,omitempty"`             // set true to indicate if fields have been encrypted
	Status      Status           `protobuf:"varint,5,opt,name=status,proto3,enum=stark.Status" json:"status,omitempty"` // describes if untagged/tagged/etc.
	// user updateable:
	Alias                   string            `protobuf:"bytes,6,opt,name=alias,proto3" json:"alias,omitempty"`                                                                                                              // the record name / human readable id (used as the default RecordKey ID)
	Description             string            `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`                                                                                                  // a short description of the record
	LocalSequencerOutputDir string            `protobuf:"bytes,9,opt,name=localSequencerOutputDir,proto3" json:"localSequencerOutputDir,omitempty"`                                                                          // where the sequencer is outputing data for this record
	LinkedSamples           map[string]string `protobuf:"bytes,10,rep,name=linkedSamples,proto3" json:"linkedSamples,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`     // all samples linked to this record (map relates sample UUIDs to a metadata location (e.g. a CID))
	LinkedLibraries         map[string]string `protobuf:"bytes,11,rep,name=linkedLibraries,proto3" json:"linkedLibraries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // all libraries linked to this record (map relates library UUIDs to a metadata location (e.g. a CID))
	Barcodes                map[string]int32  `protobuf:"bytes,12,rep,name=barcodes,proto3" json:"barcodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`              // all barcodes used by this record (map links library UUID to barcode for that library)
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stark_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_stark_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_stark_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Record) GetPreviousCID() string {
	if x != nil {
		return x.PreviousCID
	}
	return ""
}

func (x *Record) GetHistory() []*RecordComment {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Record) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *Record) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UN_INITIALIZED
}

func (x *Record) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Record) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Record) GetLocalSequencerOutputDir() string {
	if x != nil {
		return x.LocalSequencerOutputDir
	}
	return ""
}

func (x *Record) GetLinkedSamples() map[string]string {
	if x != nil {
		return x.LinkedSamples
	}
	return nil
}

func (x *Record) GetLinkedLibraries() map[string]string {
	if x != nil {
		return x.LinkedLibraries
	}
	return nil
}

func (x *Record) GetBarcodes() map[string]int32 {
	if x != nil {
		return x.Barcodes
	}
	return nil
}

//
//RecordComment is used to describe message history.
type RecordComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`     // timestamp for change
	Text        string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`               // description of the change
	PreviousCID string               `protobuf:"bytes,3,opt,name=previousCID,proto3" json:"previousCID,omitempty"` // last known CID for a Record (used to rollback the Record and undo the newly commented change)
}

func (x *RecordComment) Reset() {
	*x = RecordComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stark_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordComment) ProtoMessage() {}

func (x *RecordComment) ProtoReflect() protoreflect.Message {
	mi := &file_stark_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordComment.ProtoReflect.Descriptor instead.
func (*RecordComment) Descriptor() ([]byte, []int) {
	return file_stark_proto_rawDescGZIP(), []int{3}
}

func (x *RecordComment) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RecordComment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RecordComment) GetPreviousCID() string {
	if x != nil {
		return x.PreviousCID
	}
	return ""
}

var File_stark_proto protoreflect.FileDescriptor

var file_stark_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x6b, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x02, 0x0a, 0x06, 0x44, 0x62, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x6f, 0x64,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x50, 0x69, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x69, 0x6e, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x69,
	0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x50, 0x61, 0x69, 0x72, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x44, 0x62, 0x4d, 0x65,
	0x74, 0x61, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x50,
	0x61, 0x69, 0x72, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x50, 0x61, 0x69, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x15,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb7, 0x05, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x43, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x6f, 0x75, 0x73, 0x43, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x6c, 0x69, 0x61, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x17, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x69, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x69, 0x72, 0x12, 0x46, 0x0a,
	0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2e, 0x42, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x40, 0x0a, 0x12,
	0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x42,
	0x0a, 0x14, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x69, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x3b, 0x0a, 0x0d, 0x42, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x7f, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x43, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x43, 0x49, 0x44,
	0x2a, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e,
	0x5f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x75, 0x6e, 0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x74, 0x61, 0x67, 0x67, 0x65, 0x64, 0x10, 0x02, 0x32, 0x79, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72,
	0x6b, 0x44, 0x62, 0x12, 0x22, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0a, 0x2e, 0x73, 0x74, 0x61,
	0x72, 0x6b, 0x2e, 0x4b, 0x65, 0x79, 0x1a, 0x0d, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x0d,
	0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x0d, 0x2e,
	0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x00, 0x12, 0x23,
	0x0a, 0x04, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x0a, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x4b,
	0x65, 0x79, 0x1a, 0x0d, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x2e, 0x44, 0x62, 0x4d, 0x65, 0x74,
	0x61, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x73, 0x74, 0x61, 0x72, 0x6b, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stark_proto_rawDescOnce sync.Once
	file_stark_proto_rawDescData = file_stark_proto_rawDesc
)

func file_stark_proto_rawDescGZIP() []byte {
	file_stark_proto_rawDescOnce.Do(func() {
		file_stark_proto_rawDescData = protoimpl.X.CompressGZIP(file_stark_proto_rawDescData)
	})
	return file_stark_proto_rawDescData
}

var file_stark_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stark_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stark_proto_goTypes = []interface{}{
	(Status)(0),                 // 0: stark.Status
	(*DbMeta)(nil),              // 1: stark.DbMeta
	(*Key)(nil),                 // 2: stark.Key
	(*Record)(nil),              // 3: stark.Record
	(*RecordComment)(nil),       // 4: stark.RecordComment
	nil,                         // 5: stark.DbMeta.PairsEntry
	nil,                         // 6: stark.Record.LinkedSamplesEntry
	nil,                         // 7: stark.Record.LinkedLibrariesEntry
	nil,                         // 8: stark.Record.BarcodesEntry
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_stark_proto_depIdxs = []int32{
	5,  // 0: stark.DbMeta.Pairs:type_name -> stark.DbMeta.PairsEntry
	4,  // 1: stark.Record.history:type_name -> stark.RecordComment
	0,  // 2: stark.Record.status:type_name -> stark.Status
	6,  // 3: stark.Record.linkedSamples:type_name -> stark.Record.LinkedSamplesEntry
	7,  // 4: stark.Record.linkedLibraries:type_name -> stark.Record.LinkedLibrariesEntry
	8,  // 5: stark.Record.barcodes:type_name -> stark.Record.BarcodesEntry
	9,  // 6: stark.RecordComment.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 7: stark.StarkDb.Get:input_type -> stark.Key
	3,  // 8: stark.StarkDb.Set:input_type -> stark.Record
	2,  // 9: stark.StarkDb.Dump:input_type -> stark.Key
	3,  // 10: stark.StarkDb.Get:output_type -> stark.Record
	3,  // 11: stark.StarkDb.Set:output_type -> stark.Record
	1,  // 12: stark.StarkDb.Dump:output_type -> stark.DbMeta
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_stark_proto_init() }
func file_stark_proto_init() {
	if File_stark_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stark_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stark_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stark_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stark_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stark_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stark_proto_goTypes,
		DependencyIndexes: file_stark_proto_depIdxs,
		EnumInfos:         file_stark_proto_enumTypes,
		MessageInfos:      file_stark_proto_msgTypes,
	}.Build()
	File_stark_proto = out.File
	file_stark_proto_rawDesc = nil
	file_stark_proto_goTypes = nil
	file_stark_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StarkDbClient is the client API for StarkDb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StarkDbClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Record, error)
	Set(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Record, error)
	Dump(ctx context.Context, in *Key, opts ...grpc.CallOption) (*DbMeta, error)
}

type starkDbClient struct {
	cc grpc.ClientConnInterface
}

func NewStarkDbClient(cc grpc.ClientConnInterface) StarkDbClient {
	return &starkDbClient{cc}
}

func (c *starkDbClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/stark.StarkDb/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starkDbClient) Set(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/stark.StarkDb/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starkDbClient) Dump(ctx context.Context, in *Key, opts ...grpc.CallOption) (*DbMeta, error) {
	out := new(DbMeta)
	err := c.cc.Invoke(ctx, "/stark.StarkDb/Dump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarkDbServer is the server API for StarkDb service.
type StarkDbServer interface {
	Get(context.Context, *Key) (*Record, error)
	Set(context.Context, *Record) (*Record, error)
	Dump(context.Context, *Key) (*DbMeta, error)
}

// UnimplementedStarkDbServer can be embedded to have forward compatible implementations.
type UnimplementedStarkDbServer struct {
}

func (*UnimplementedStarkDbServer) Get(context.Context, *Key) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedStarkDbServer) Set(context.Context, *Record) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedStarkDbServer) Dump(context.Context, *Key) (*DbMeta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dump not implemented")
}

func RegisterStarkDbServer(s *grpc.Server, srv StarkDbServer) {
	s.RegisterService(&_StarkDb_serviceDesc, srv)
}

func _StarkDb_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarkDbServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stark.StarkDb/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarkDbServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarkDb_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarkDbServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stark.StarkDb/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarkDbServer).Set(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarkDb_Dump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarkDbServer).Dump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stark.StarkDb/Dump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarkDbServer).Dump(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

var _StarkDb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stark.StarkDb",
	HandlerType: (*StarkDbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _StarkDb_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _StarkDb_Set_Handler,
		},
		{
			MethodName: "Dump",
			Handler:    _StarkDb_Dump_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stark.proto",
}
